name = "StableTrees"
uuid = "9113e207-2504-4b06-8eee-d78e288bee65"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "1.0.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AbstractTrees = "0.3"
CategoricalArrays = "0.10"
MLJModelInterface = "1.4"
Tables = "1.7"
julia = "1.6"
