[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
SIRUS = "cdeec39e-fb35-4959-aadb-a1dd5dede958"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[compat]
CSV = "0.10"
CairoMakie = "0.12"
CategoricalArrays = "0.10"
DataDeps = "0.7"
DataFrames = "1"
DecisionTree = "0.12"
Documenter = "1"
EvoTrees = "0.16"
LiveServer = "1"
MLJ = "0.20"
MLJBase = "1"
MLJDecisionTreeInterface = "0.4"
PlutoStaticHTML = "6"
PlutoUI = "0.7"
StableRNGs = "1"
